export const Data = [
    {
        client: "Aline Johnson",
        country: "Canada",
        email: "aline@gmail.com",
        project: "AI Research Platform",
        progress: "10",
        status: "Completed",
        date: "10/03/2023",
        image: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Michael Thompson",
        country: "Germany",
        email: "michael@gmail.com",
        project: "JS Research Platform",
        progress: "30",
        status: "In Progress",
        date: "14/05/2023",
        image: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Sofia Lee",
        country: "Australia",
        email: "sofia@gmail.com",
        project: "E-Learning Platform",
        progress: "100",
        status: "Completed",
        date: "04/04/2023",
        image: "https://images.pexels.com/photos/2415938/pexels-photo-2415938.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Lucas Yue",
        country: "Canada",
        email: "lucas@gmail.com",
        project: "Mobile Payment App",
        progress: "50",
        status: "In Progress",
        date: "15/09/2023",
        image: "https://images.pexels.com/photos/2072453/pexels-photo-2072453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Ava kimy",
        country: "Sounth korea",
        email: "ava@gmail.com",
        project: "Smart Home App",
        progress: "53",
        status: "In Progress",
        date: "05/09/2023",
        image: "https://images.pexels.com/photos/10361760/pexels-photo-10361760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Ethan Davis",
        country: "New Zealand",
        email: "ethan@gmail.com",
        project: "Virtual Reality App",
        progress: "08",
        status: "In Progress",
        date: "11/09/2023",
        image: "https://images.pexels.com/photos/3777946/pexels-photo-3777946.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Isabella Rossi",
        country: "Italy",
        email: "ethan@gmail.com",
        project: "E-Commerce Platform",
        progress: "38",
        status: "In Progress",
        date: "16/02/2023",
        image: "https://images.pexels.com/photos/1800456/pexels-photo-1800456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Emma Martinez",
        country: "Argentina",
        email: "emma@gmail.com",
        project: "HR Platform",
        progress: "13",
        status: "In Progress",
        date: "12/09/2023",
        image: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Lucas Perez",
        country: "Mexico",
        email: "lucas@gmail.com",
        project: "Payment App Platform",
        progress: "50",
        status: "In Progress",
        date: "10/07/2023",
        image: "https://images.pexels.com/photos/1808401/pexels-photo-1808401.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Noah Garcia",
        country: "Spain",
        email: "noah@gmail.com",
        project: "Tourism WebSite",
        progress: "80",
        status: "Completed",
        date: "12/08/2023",
        image: "https://images.pexels.com/photos/1212984/pexels-photo-1212984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Liam Patel",
        country: "India",
        email: "liam@gmail.com",
        project: "Agritech Plataform",
        progress: "100",
        status: "Completed",
        date: "29/10/2023",
        image: "https://images.pexels.com/photos/936090/pexels-photo-936090.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Olivia Chen",
        country: "China",
        email: "olivia@gmail.com",
        project: "HR Assistant",
        progress: "23",
        status: "In Progress",
        date: "10/11/2023",
        image: "https://images.pexels.com/photos/3273969/pexels-photo-3273969.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "Mia Williams",
        country: "USA",
        email: "mia@gmail.com",
        project: "Cloud Storage Solution",
        progress: "45",
        status: "In Progress",
        date: "30/11/2023",
        image: "https://images.pexels.com/photos/785667/pexels-photo-785667.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

    {
        client: "WilliaTanaka",
        country: "Japan",
        email: "william@gmail.com",
        project: "Device app integration",
        progress: "73",
        status: "In Progress",
        date: "29/06/2023",
        image: "https://images.pexels.com/photos/2272786/pexels-photo-2272786.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    },

]